version: '3.5'
services:

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    hostname: phpmyadmin
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - PMA_HOST=random-id-mysql
    networks:
      random-network:
        aliases:
          - phpmyadmin
    depends_on:
      - random-id-mysql
    ports:
      - 8001:80

  random-id-mysql:
    image: mariadb
    restart: always
    container_name: random-id-mysql
    hostname: random-id-mysql
    environment:
      - MYSQL_DATABASE=UNIQUE_ID
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'
    expose:
      - '3306'
      # Where our data will be persisted
    volumes:
      - mysql-db:/var/lib/mysql
    networks:
      random-network:
        aliases:
          - random-id-mysql

volumes:
  mysql-db:

networks:
  random-network:
    name: random-network
    driver: bridge